# Generated by Django 5.2.5 on 2025-11-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
