# Generated by Django 5.2.5 on 2025-11-26 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0002_stock_dosage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInvoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_id', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=120)),
                ('billing_staff', models.CharField(max_length=120)),
                ('staff_id', models.CharField(max_length=40)),
                ('patient_type', models.CharField(choices=[('Outpatient', 'Outpatient'), ('Inpatient', 'Inpatient')], max_length=20)),
                ('address_text', models.CharField(max_length=255)),
                ('payment_type', models.CharField(max_length=60)),
                ('payment_status', models.CharField(max_length=60)),
                ('payment_mode', models.CharField(max_length=60)),
                ('bill_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sgst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pharmacy_invoice_history',
            },
        ),
        migrations.CreateModel(
            name='PharmacyInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('item_code', models.CharField(max_length=30)),
                ('drug_name', models.CharField(max_length=120)),
                ('rack_no', models.CharField(max_length=20)),
                ('shelf_no', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='HMS_backend.pharmacyinvoicehistory')),
            ],
            options={
                'db_table': 'pharmacy_invoice_item',
            },
        ),
    ]
