# Generated by Django 5.2.5 on 2025-12-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0003_pharmacyinvoicehistory_pharmacyinvoiceitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='HospitalInvoiceHistory',
        ),
        migrations.AlterModelTable(
            name='hospitalinvoicehistory',
            table='hospital_invoice_history',
        ),
    ]
