# Generated by Django 5.2.5 on 2025-12-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0004_rename_invoice_hospitalinvoicehistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('normal', 'Normal'), ('severe', 'Severe'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('active', 'Active'), ('inactive', 'Inactive'), ('emergency', 'Emergency')], default='new', max_length=20),
        ),
    ]
