# Generated by Django 5.2.5 on 2025-12-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalinvoicehistory',
            name='invoice_items',
        ),
        migrations.AlterField(
            model_name='hospitalinvoicehistory',
            name='email',
            field=models.CharField(default='patient@hospital.com', max_length=100),
        ),
        migrations.CreateModel(
            name='HospitalInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveSmallIntegerField(help_text='Serial number in invoice')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='HMS_backend.hospitalinvoicehistory')),
            ],
            options={
                'verbose_name': 'Hospital Invoice Item',
                'verbose_name_plural': 'Hospital Invoice Items',
                'db_table': 'hospital_invoice_item',
                'ordering': ['s_no'],
            },
        ),
    ]
