# Generated by Django 5.2.5 on 2025-12-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0006_remove_hospitalinvoicehistory_invoice_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Recently Donated', 'Recently Donated')], default='Not Eligible', max_length=20),
        ),
    ]
