# Generated by Django 5.2.5 on 2025-12-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0007_donor_email_alter_donor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible')], default='Not Eligible', max_length=20),
        ),
    ]
