# Generated by Django 5.2.5 on 2025-12-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0008_alter_donor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
    ]
