# Generated by Django 5.2.5 on 2025-12-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0009_remove_donor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodgroup',
            name='created_at',
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='status',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Adequate', 'Adequate'), ('Full', 'Full')], default='Adequate', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
