# Generated by Django 5.2.5 on 2025-12-05 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0010_remove_bloodgroup_created_at_donor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.AddField(
            model_name='bloodgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
    ]
