# Generated by Django 5.2.5 on 2025-12-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0012_donor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='eligibility_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_eligibility_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
