# Generated by Django 5.2.5 on 2025-12-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0015_remove_appointment_room_no_appointment_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='bed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='room_no',
            field=models.CharField(blank=True, default='No bed assigned', max_length=20, null=True),
        ),
    ]
