# Generated by Django 5.2.5 on 2025-12-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0016_remove_appointment_bed_appointment_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('in-patient', 'In-Patient'), ('out-patient', 'Out-Patient')], default='in-patient', max_length=20),
        ),
    ]
