# Generated by Django 5.2.5 on 2026-01-13 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0020_medicaltest_labreport_file_path_treatmentcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineallocation',
            name='billing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='medicineallocation',
            name='pharmacy_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HMS_backend.pharmacyinvoicehistory'),
        ),
    ]
