# Generated by Django 5.2.5 on 2026-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_backend', '0022_staff_surgery_count_surgery'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='Sravan Multispeciality Hospital', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logo/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='Working hours in JSON format')),
                ('system_preferences', models.JSONField(blank=True, default=dict, help_text='System preferences and configurations')),
            ],
            options={
                'verbose_name': 'Hospital Information',
                'verbose_name_plural': 'Hospital Information',
                'db_table': 'hospital_settings',
            },
        ),
    ]
